version: "3.9"

services:

  default_rails_app:
    build:
      context: .
      #args:
      #  USER_ID: "${USER_ID:-1000}"
      #  GROUP_ID: "${GROUP_ID:-1000}"
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
